### ISSUE TITLE
Error when running lsl_loadlib()

### ISSUE THREAD

**Issue by digitalgreentea** [sccn/labstreaminglayer#341] opened 2018-08-31 19:10 UTC
When I enter lsl_loadlib() into MATLAB I receive the following error:

http://i66.tinypic.com/2hydp8g.png

I am using this repository to load the LSL data: https://github.com/OpenBCI/OpenBCI_MATLAB

How can I resolve this?

**Comment by dmedine** [comment] 2018-09-01 06:32
Have you posted this on the OpenBCI forums? The problem is that the mex 
files (matlab executables) that they provide are incompatible with your 
system for whatever reason. You are using a 64-bit Mac, I take it? I'm 
not sure why this should be, but Matlab is sometimes touchy about this, 
it could have to do with the version of Matlab you have.

You can try re-building the mex files. There is a script that does this 
in the LSL repo 
(https://github.com/sccn/labstreaminglayer/blob/master/LSL/liblsl-Matlab/build_mex.m), 
but I don't know if the OpenBCI fork has the up to date source code for 
LSL. Regardless, you will need to have some build tools installed, 
either xcode or some other tool chain (last I checked Apple forces users 
to get xcode in order to use gcc, which is one of the reasons that I 
don't touch Apple computers anymore).

You can also try replacing the offending mex files in 
<path_to>liblsl-Matlab/mex/<etc.> with ones from the SCCN ftp: 
ftp://sccn.ucsd.edu/pub/software/LSL/SDK/liblsl-Matlab-1.11.zip

**Comment by dmedine** [comment] 2018-09-01 06:33
I am closing this as it is an issue with OpenBCI's repository, not this one.

**Closed by dmedine** 2018-09-01 06:33 UTC
