### ISSUE TITLE
Java Wrapper Bad Type Conversions

### ISSUE THREAD

**Issue by Shaffer319** [sccn/labstreaminglayer#159] opened 2016-12-05 18:49 UTC
I am trying to use the JNA wrapped Java version of you library with 64bit java and on the Android device to catch error such as disconnect and rethrow them correctly in java. The edu.ucsd.sccn.LSL library is causing null pointer exception when trying to resolve streams on the android device using gcc for armeabi-v7a. 

```Java
public interface dll extends Library {
    ...
    int lsl_resolve_byprop(Pointer[] buffer, long buffer_elements, String prop, String value, int minimum, double wait_time);
    ...
}
````
```C++
LIBLSL_C_API int lsl_resolve_byprop(lsl_streaminfo *buffer, unsigned buffer_elements, char *prop, char *value, int minimum, double timeout) {
    try {
         // create a new resolver
        resolver_impl resolver;
        // build a new query.
        // This line throws NULL pointer while accessing the char* prop due to buffer_elements being the wrong size 
        std::ostringstream os; os << "session_id='" << api_config::get_instance()->session_id() << "' and " << prop << "='" << value << "'";
    ...
}
```

This and others function passing defining `long` should actually be `int`.

Looking at the type mapping for the JNA java `long` is is always c/c++ `long long, __int64 = 64-bit integer`.
http://java-native-access.github.io/jna/4.2.1/

`unsigned` is and `unsigned int`
http://en.cppreference.com/w/cpp/language/types

To get the correct value for unsigned buffer_elements JNA recommends 
Unsigned values may be passed by assigning the corresponding two's-complement representation to the signed type of the same size.

Current fix for just this function:
```Java
public interface dll extends Library {
    ...
    int lsl_resolve_byprop(Pointer[] buffer, int buffer_elements, String prop, String value, int minimum, double wait_time);
    ...
}
````

Any function passing a java `long` to an `unsigned`/`unsigned int` will need to be changed.

**Comment by Shaffer319** [comment] 2016-12-05 19:40
Maybe it would be better to make all the buffer sizes the same data type. Some `*_elements` are `unsigned`, `int`, or `unsigned long`

**Comment by mgrivich** [comment] 2016-12-05 23:34
Have you gotten JNA working with Android, or is this more of a preliminary investigation? No effort has been made by us to make JNA work with Android (though I expect that it is possible). We have been using SWIG for that. Instructions on getting LSL to work with Android are at https://github.com/sccn/labstreaminglayer/tree/master/LSL/liblsl-Android or https://github.com/sccn/labstreaminglayer/tree/master/LSL/liblsl-Android/android-vs2013.

**Comment by Shaffer319** [comment] 2016-12-06 01:04
They seem to support Android and have precompiled binaries. It seemed to work on android just fine once I changed the type in the JNA. I wanted to write an app in java and port it to Android. 

This Issues seems like more of a **Java/JNA issue** than an Android issue.  JNA cause a null pointer issue that could show up on any architecture if I read the documentation correctly. The original swig version seemed to crash when an inlet stream using the ReceiveStringMarkers.java disconnected without a source_id set. I wanted to use the JNA because it seemed to work on windows and rethrew the error as java errors that I could handle instead of crashing.

I used the JNA distro from the following link for my Android device. Yours maybe different.
https://github.com/java-native-access/jna/blob/master/dist/android-armv7.jar

Following the instructions for the Eclipse android in Android Studio you can unzip the jar and move the libjnidispatch.so file to the correct native /app/src/main/jniLibs/<architecture>/. Using `LSL.ResolveStreams();` worked fine but `LSL.ResolveStream("type","Markers");` with the Null Pointer.

**Comment by Shaffer319** [comment] 2016-12-07 20:43
I checked if it was Android or Java/JNA. Using X86 version of java on Windows x64 caused a similar issue when using:
`LSL.StreamInfo[] infos = LSL.resolve_stream("type", "cmd");`
```Java
Exception in thread "Thread-1" Press enter to resolve more streams.
java.lang.Error: Invalid memory access
	at com.sun.jna.Native.invokeInt(Native Method)
	at com.sun.jna.Function.invoke(Function.java:390)
	at com.sun.jna.Function.invoke(Function.java:323)
	at com.sun.jna.Library$Handler.invoke(Library.java:236)
	at com.sun.proxy.$Proxy0.lsl_resolve_byprop(Unknown Source)
	at edu.ucsd.sccn.LSL.resolve_stream(LSL.java:455)
	at edu.ucsd.sccn.LSL.resolve_stream(LSL.java:462)
	at edu.ucsd.sccn.examples.GetAllStreams$2.run(GetAllStreams.java:44)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by mgrivich** [comment] 2016-12-09 18:53
Okay, it looks like the problem is with JNA. I'm not one who committed that code. Maybe it was Christian? It was in the google code days, so the record has been lost. I'm pretty busy at the moment, but if no one else takes care of it I should be able to look into it in January.

**Comment by mgrivich** [comment] 2017-01-11 19:23
Thank you for your effort on this issue. I have fixed it in the master branch.

**Closed by mgrivich** 2017-01-11 19:23 UTC
